"""add default to tasks updated_at

Revision ID: f71c7cb2533e
Revises: 7c3032f34897
Create Date: 2026-02-13 02:36:02.780694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f71c7cb2533e'
down_revision: Union[str, Sequence[str], None] = '7c3032f34897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.func.now(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
