"""add username with data migration

Revision ID: fc88c71fd0d6
Revises: f71c7cb2533e
Create Date: 2026-02-13 11:31:00.561118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc88c71fd0d6'
down_revision: Union[str, Sequence[str], None] = 'f71c7cb2533e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=True))

    op.execute("UPDATE users SET username = email")

    op.alter_column('users', 'username', nullable=False)


    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
